### ISSUE TITLE
ilp-plugin-bigchaindb@0.0.2 postinstall: `npm run build:dist` npm ERR! Exit status 1

### ISSUE THREAD

**Issue by pards** [bigchaindb/ilp-plugin-bigchaindb#3]
I get the following error when trying to run the BigChainDB examples in Docker on Ubuntu 16.04

The error log isn't available because it's inside the container.

`$ docker-compose up`

`npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.13
npm WARN extract-text-webpack-plugin@1.0.1 requires a peer of webpack@^1.9.11 but none was installed.
npm WARN webpack-dev-server@1.14.1 requires a peer of webpack@>=1.3.0 <3 but none was installed.
npm ERR! Linux 4.4.0-28-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.3.0
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

npm ERR! ilp-plugin-bigchaindb@0.0.2 postinstall: `npm run build:dist`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ilp-plugin-bigchaindb@0.0.2 postinstall script 'npm run build:dist'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ilp-plugin-bigchaindb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build:dist
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ilp-plugin-bigchaindb
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ilp-plugin-bigchaindb
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/src/app/client/npm-debug.log
ERROR: Service 'js' failed to build: The command '/bin/sh -c npm install' returned a non-zero code: 1
`

**Comment by sohkai** [comment]
Hey @pards, thanks for checking it out! Looks like the examples might be using an older version; it says it's trying to load 0.0.2 but now we're at 0.0.7 with a bunch of platform fixes.

**Comment by sohkai** [comment]
Ahh, turns out we've pinned the version; you can bump it up yourself locally (in `client/package.json`; look for `ilp-plugin-bigchaindb` and rev it up to `0.0.7`) and try it, otherwise I'm doing it locally now and will let you know when I've pushed.

Another thing you could try, if you wanted to see the interledger demos, is [this PR](https://github.com/bigchaindb/bigchaindb-examples/pull/28) that sets up multiple instances of BigchainDB through Docker and has a nice make file for configuration. It should also build correctly :).

**Comment by pards** [comment]
Thanks, updating the package.json worked for getting beyond the build issue.

**Comment by sohkai** [comment]
Ok, so looking into this a bit further, the docker configuration on the current master branch for the repo is outdated and likely won't work. Using the PR I linked to above will probably yield more success, but I'm working on updating the current docker file.

**Comment by pards** [comment]
Yeah. I created another issue in the examples project related to the docker images
https://github.com/bigchaindb/bigchaindb-examples/issues/30

**Comment by sohkai** [comment]
👍 I'll close this issue then and we'll work off of that one.
